-- +goose Up
-- +goose StatementBegin
SELECT
    'up SQL query';




CREATE TABLE products (
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    published_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT now(),
    updated_at TIMESTAMP NULL DEFAULT now(),
    deleted_at TIMESTAMP NULL DEFAULT NULL
);




-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
SELECT
    'down SQL query';




DROP TABLE IF EXISTS products;




-- +goose StatementEnd
