-- +goose Up
-- +goose StatementBegin
SELECT
    'up SQL query';




CREATE TABLE users (
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT now(),
    updated_at TIMESTAMP NULL DEFAULT now(),
    deleted_at TIMESTAMP NULL DEFAULT NULL
);




-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
SELECT
    'down SQL query';




DROP TABLE IF EXISTS users;




-- +goose StatementEnd
