-- +goose Up
-- +goose StatementBegin
SELECT
    'up SQL query';




CREATE TABLE user_roles (
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT now(),
    updated_at TIMESTAMP NULL DEFAULT now(),
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);




CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);




-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
SELECT
    'down SQL query';




DROP TABLE IF EXISTS user_roles;




-- +goose StatementEnd
