package domain

import "strings"

type CountryCode string

func (cc CountryCode) IsValid() bool {
	for _, c := range Countries() {
		if strings.EqualFold(string(c.Code), string(cc)) {
			return true
		}
	}
	return false
}

func (cc CountryCode) Options() []CountryCode { return countryCodes }
func (cc CountryCode) String() string         { return string(cc) }

var countryCodes = func() []CountryCode {
	ccs := make([]CountryCode, len(Countries()))
	for i, c := range Countries() {
		ccs[i] = c.Code
	}
	return ccs
}()

type Country struct {
	Code CountryCode
	Name string
}

func NewCountry(code CountryCode, name string) Country {
	return Country{
		Code: code,
		Name: name,
	}
}

func Countries() []Country { return countries }

// CountryCode in ISO 3166-1 alpha-3 format
var countries = []Country{
	NewCountry("AFG", "Afghanistan"),
	NewCountry("ALA", "Åland Islands"),
	NewCountry("ALB", "Albania"),
	NewCountry("DZA", "Algeria"),
	NewCountry("ASM", "American Samoa"),
	NewCountry("AND", "Andorra"),
	NewCountry("AGO", "Angola"),
	NewCountry("AIA", "Anguilla"),
	NewCountry("ATA", "Antarctica"),
	NewCountry("ATG", "Antigua and Barbuda"),
	NewCountry("ARG", "Argentina"),
	NewCountry("ARM", "Armenia"),
	NewCountry("ABW", "Aruba"),
	NewCountry("AUS", "Australia"),
	NewCountry("AUT", "Austria"),
	NewCountry("AZE", "Azerbaijan"),
	NewCountry("BHS", "Bahamas"),
	NewCountry("BHR", "Bahrain"),
	NewCountry("BGD", "Bangladesh"),
	NewCountry("BRB", "Barbados"),
	NewCountry("BLR", "Belarus"),
	NewCountry("BEL", "Belgium"),
	NewCountry("BLZ", "Belize"),
	NewCountry("BEN", "Benin"),
	NewCountry("BMU", "Bermuda"),
	NewCountry("BTN", "Bhutan"),
	NewCountry("BOL", "Bolivia, Plurinational State of"),
	NewCountry("BES", "Bonaire, Sint Eustatius and Saba"),
	NewCountry("BIH", "Bosnia and Herzegovina"),
	NewCountry("BWA", "Botswana"),
	NewCountry("BVT", "Bouvet Island"),
	NewCountry("BRA", "Brazil"),
	NewCountry("IOT", "British Indian Ocean Territory"),
	NewCountry("BRN", "Brunei Darussalam"),
	NewCountry("BGR", "Bulgaria"),
	NewCountry("BFA", "Burkina Faso"),
	NewCountry("BDI", "Burundi"),
	NewCountry("KHM", "Cambodia"),
	NewCountry("CMR", "Cameroon"),
	NewCountry("CAN", "Canada"),
	NewCountry("CPV", "Cape Verde"),
	NewCountry("CYM", "Cayman Islands"),
	NewCountry("CAF", "Central African Republic"),
	NewCountry("TCD", "Chad"),
	NewCountry("CHL", "Chile"),
	NewCountry("CHN", "China"),
	NewCountry("CXR", "Christmas Island"),
	NewCountry("CCK", "Cocos (Keeling) Islands"),
	NewCountry("COL", "Colombia"),
	NewCountry("COM", "Comoros"),
	NewCountry("COG", "Congo"),
	NewCountry("COD", "Congo, the Democratic Republic of the"),
	NewCountry("COK", "Cook Islands"),
	NewCountry("CRI", "Costa Rica"),
	NewCountry("CIV", "Côte d'Ivoire"),
	NewCountry("HRV", "Croatia"),
	NewCountry("CUB", "Cuba"),
	NewCountry("CUW", "Curaçao"),
	NewCountry("CYP", "Cyprus"),
	NewCountry("CZE", "Czech Republic"),
	NewCountry("DNK", "Denmark"),
	NewCountry("DJI", "Djibouti"),
	NewCountry("DMA", "Dominica"),
	NewCountry("DOM", "Dominican Republic"),
	NewCountry("ECU", "Ecuador"),
	NewCountry("EGY", "Egypt"),
	NewCountry("SLV", "El Salvador"),
	NewCountry("GNQ", "Equatorial Guinea"),
	NewCountry("ERI", "Eritrea"),
	NewCountry("EST", "Estonia"),
	NewCountry("ETH", "Ethiopia"),
	NewCountry("FLK", "Falkland Islands (Malvinas)"),
	NewCountry("FRO", "Faroe Islands"),
	NewCountry("FJI", "Fiji"),
	NewCountry("FIN", "Finland"),
	NewCountry("FRA", "France"),
	NewCountry("GUF", "French Guiana"),
	NewCountry("PYF", "French Polynesia"),
	NewCountry("ATF", "French Southern Territories"),
	NewCountry("GAB", "Gabon"),
	NewCountry("GMB", "Gambia"),
	NewCountry("GEO", "Georgia"),
	NewCountry("DEU", "Germany"),
	NewCountry("GHA", "Ghana"),
	NewCountry("GIB", "Gibraltar"),
	NewCountry("GRC", "Greece"),
	NewCountry("GRL", "Greenland"),
	NewCountry("GRD", "Grenada"),
	NewCountry("GLP", "Guadeloupe"),
	NewCountry("GUM", "Guam"),
	NewCountry("GTM", "Guatemala"),
	NewCountry("GGY", "Guernsey"),
	NewCountry("GIN", "Guinea"),
	NewCountry("GNB", "Guinea-Bissau"),
	NewCountry("GUY", "Guyana"),
	NewCountry("HTI", "Haiti"),
	NewCountry("HMD", "Heard Island and McDonald Islands"),
	NewCountry("VAT", "Holy See (Vatican City State)"),
	NewCountry("HND", "Honduras"),
	NewCountry("HKG", "Hong Kong"),
	NewCountry("HUN", "Hungary"),
	NewCountry("ISL", "Iceland"),
	NewCountry("IND", "India"),
	NewCountry("IDN", "Indonesia"),
	NewCountry("IRN", "Iran, Islamic Republic of"),
	NewCountry("IRQ", "Iraq"),
	NewCountry("IRL", "Ireland"),
	NewCountry("IMN", "Isle of Man"),
	NewCountry("ISR", "Israel"),
	NewCountry("ITA", "Italy"),
	NewCountry("JAM", "Jamaica"),
	NewCountry("JPN", "Japan"),
	NewCountry("JEY", "Jersey"),
	NewCountry("JOR", "Jordan"),
	NewCountry("KAZ", "Kazakhstan"),
	NewCountry("KEN", "Kenya"),
	NewCountry("KIR", "Kiribati"),
	NewCountry("PRK", "Korea, Democratic People's Republic of"),
	NewCountry("KOR", "Korea, Republic of"),
	NewCountry("KWT", "Kuwait"),
	NewCountry("KGZ", "Kyrgyzstan"),
	NewCountry("LAO", "Lao People's Democratic Republic"),
	NewCountry("LVA", "Latvia"),
	NewCountry("LBN", "Lebanon"),
	NewCountry("LSO", "Lesotho"),
	NewCountry("LBR", "Liberia"),
	NewCountry("LBY", "Libya"),
	NewCountry("LIE", "Liechtenstein"),
	NewCountry("LTU", "Lithuania"),
	NewCountry("LUX", "Luxembourg"),
	NewCountry("MAC", "Macao"),
	NewCountry("MKD", "Macedonia, the former Yugoslav Republic of"),
	NewCountry("MDG", "Madagascar"),
	NewCountry("MWI", "Malawi"),
	NewCountry("MYS", "Malaysia"),
	NewCountry("MDV", "Maldives"),
	NewCountry("MLI", "Mali"),
	NewCountry("MLT", "Malta"),
	NewCountry("MHL", "Marshall Islands"),
	NewCountry("MTQ", "Martinique"),
	NewCountry("MRT", "Mauritania"),
	NewCountry("MUS", "Mauritius"),
	NewCountry("MYT", "Mayotte"),
	NewCountry("MEX", "Mexico"),
	NewCountry("FSM", "Micronesia, Federated States of"),
	NewCountry("MDA", "Moldova, Republic of"),
	NewCountry("MCO", "Monaco"),
	NewCountry("MNG", "Mongolia"),
	NewCountry("MNE", "Montenegro"),
	NewCountry("MSR", "Montserrat"),
	NewCountry("MAR", "Morocco"),
	NewCountry("MOZ", "Mozambique"),
	NewCountry("MMR", "Myanmar"),
	NewCountry("NAM", "Namibia"),
	NewCountry("NRU", "Nauru"),
	NewCountry("NPL", "Nepal"),
	NewCountry("NLD", "Netherlands"),
	NewCountry("NCL", "New Caledonia"),
	NewCountry("NZL", "New Zealand"),
	NewCountry("NIC", "Nicaragua"),
	NewCountry("NER", "Niger"),
	NewCountry("NGA", "Nigeria"),
	NewCountry("NIU", "Niue"),
	NewCountry("NFK", "Norfolk Island"),
	NewCountry("MNP", "Northern Mariana Islands"),
	NewCountry("NOR", "Norway"),
	NewCountry("OMN", "Oman"),
	NewCountry("PAK", "Pakistan"),
	NewCountry("PLW", "Palau"),
	NewCountry("PSE", "Palestinian Territory, Occupied"),
	NewCountry("PAN", "Panama"),
	NewCountry("PNG", "Papua New Guinea"),
	NewCountry("PRY", "Paraguay"),
	NewCountry("PER", "Peru"),
	NewCountry("PHL", "Philippines"),
	NewCountry("PCN", "Pitcairn"),
	NewCountry("POL", "Poland"),
	NewCountry("PRT", "Portugal"),
	NewCountry("PRI", "Puerto Rico"),
	NewCountry("QAT", "Qatar"),
	NewCountry("REU", "Réunion"),
	NewCountry("ROU", "Romania"),
	NewCountry("RUS", "Russian Federation"),
	NewCountry("RWA", "Rwanda"),
	NewCountry("BLM", "Saint Barthélemy"),
	NewCountry("SHN", "Saint Helena, Ascension and Tristan da Cunha"),
	NewCountry("KNA", "Saint Kitts and Nevis"),
	NewCountry("LCA", "Saint Lucia"),
	NewCountry("MAF", "Saint Martin (French part)"),
	NewCountry("SPM", "Saint Pierre and Miquelon"),
	NewCountry("VCT", "Saint Vincent and the Grenadines"),
	NewCountry("WSM", "Samoa"),
	NewCountry("SMR", "San Marino"),
	NewCountry("STP", "Sao Tome and Principe"),
	NewCountry("SAU", "Saudi Arabia"),
	NewCountry("SEN", "Senegal"),
	NewCountry("SRB", "Serbia"),
	NewCountry("SYC", "Seychelles"),
	NewCountry("SLE", "Sierra Leone"),
	NewCountry("SGP", "Singapore"),
	NewCountry("SXM", "Sint Maarten (Dutch part)"),
	NewCountry("SVK", "Slovakia"),
	NewCountry("SVN", "Slovenia"),
	NewCountry("SLB", "Solomon Islands"),
	NewCountry("SOM", "Somalia"),
	NewCountry("ZAF", "South Africa"),
	NewCountry("SGS", "South Georgia and the South Sandwich Islands"),
	NewCountry("SSD", "South Sudan"),
	NewCountry("ESP", "Spain"),
	NewCountry("LKA", "Sri Lanka"),
	NewCountry("SDN", "Sudan"),
	NewCountry("SUR", "Suriname"),
	NewCountry("SJM", "Svalbard and Jan Mayen"),
	NewCountry("SWZ", "Swaziland"),
	NewCountry("SWE", "Sweden"),
	NewCountry("CHE", "Switzerland"),
	NewCountry("SYR", "Syrian Arab Republic"),
	NewCountry("TWN", "Taiwan, Province of China"),
	NewCountry("TJK", "Tajikistan"),
	NewCountry("TZA", "Tanzania, United Republic of"),
	NewCountry("THA", "Thailand"),
	NewCountry("TLS", "Timor-Leste"),
	NewCountry("TGO", "Togo"),
	NewCountry("TKL", "Tokelau"),
	NewCountry("TON", "Tonga"),
	NewCountry("TTO", "Trinidad and Tobago"),
	NewCountry("TUN", "Tunisia"),
	NewCountry("TUR", "Turkey"),
	NewCountry("TKM", "Turkmenistan"),
	NewCountry("TCA", "Turks and Caicos Islands"),
	NewCountry("TUV", "Tuvalu"),
	NewCountry("UGA", "Uganda"),
	NewCountry("UKR", "Ukraine"),
	NewCountry("ARE", "United Arab Emirates"),
	NewCountry("GBR", "United Kingdom"),
	NewCountry("USA", "United States"),
	NewCountry("UMI", "United States Minor Outlying Islands"),
	NewCountry("URY", "Uruguay"),
	NewCountry("UZB", "Uzbekistan"),
	NewCountry("VUT", "Vanuatu"),
	NewCountry("VEN", "Venezuela, Bolivarian Republic of"),
	NewCountry("VNM", "Viet Nam"),
	NewCountry("VGB", "Virgin Islands, British"),
	NewCountry("VIR", "Virgin Islands, U.S."),
	NewCountry("WLF", "Wallis and Futuna"),
	NewCountry("ESH", "Western Sahara"),
	NewCountry("YEM", "Yemen"),
	NewCountry("ZMB", "Zambia"),
	NewCountry("ZWE", "Zimbabwe"),
}
