-- +goose Up
SELECT
    'up SQL query';




CREATE TABLE token_credentials (
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    client_id VARCHAR(255) NOT NULL,
    client_secret VARCHAR(255) NOT NULL,
    login_method VARCHAR(255) NOT NULL,
    login_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);




-- +goose Down
SELECT
    'down SQL query';




DROP TABLE IF EXISTS token_credentials;
