-- +goose Up
SELECT
    'up SQL query';




CREATE TABLE users (
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP NULL DEFAULT NULL
);




-- +goose Down
SELECT
    'down SQL query';




DROP TABLE IF EXISTS users;
