-- +goose Up
SELECT
    'up SQL query';




CREATE TABLE user_roles (
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);




-- +goose Down
SELECT
    'down SQL query';




DROP TABLE IF EXISTS user_roles;
